name: tier-zero

services:
  synnax:
    image: synnaxlabs/synnax:latest
    restart: unless-stopped
    ports:
      - 9095:9095
    volumes:
      - synnax-data:/usr/local/synnax/data
    command: ["-d", "/usr/local/synnax/data", "-i", "-l", "synnax:9095"]
    hostname: synnax
    networks:
      - app-network

  etcd0:
    image: bitnami/etcd:latest
    container_name: etcd0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=lavin-cluster
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app-network

  etcd1:
    image: bitnami/etcd:latest
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=lavin-cluster
    ports:
      - "2381:2379"
      - "2382:2380"
    networks:
      - app-network

  etcd2:
    image: bitnami/etcd:latest
    container_name: etcd2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=lavin-cluster
    ports:
      - "2383:2379"
      - "2384:2380"
    networks:
      - app-network

  lavinmq0:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq0
    ports:
      - "5672:5672"
      - "5679:5679"
      - "15672:15672"
    environment:
      - LAVINMQ__ETCD__ENDPOINTS=http://etcd0:2379,http://etcd1:2379,http://etcd2:2379
    volumes:
      - lavinmq0-data:/var/lib/lavinmq/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    networks:
      - app-network

  lavinmq1:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq1
    ports:
      - "5673:5672"
      - "5680:5679"
      - "15673:15672"
    environment:
      - LAVINMQ__ETCD__ENDPOINTS=http://etcd0:2379,http://etcd1:2379,http://etcd2:2379
    volumes:
      - lavinmq1-data:/var/lib/lavinmq/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    networks:
      - app-network

  lavinmq2:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq2
    ports:
      - "5674:5672"
      - "5681:5679"
      - "15674:15672"
    environment:
      - LAVINMQ__ETCD__ENDPOINTS=http://etcd0:2379,http://etcd1:2379,http://etcd2:2379
    volumes:
      - lavinmq2-data:/var/lib/lavinmq/data
    depends_on:
      - etcd0
      - etcd1
      - etcd2
    networks:
      - app-network

  lavinmq0-nginx:
    image: nginx:alpine
    container_name: lavinmq0-nginx
    ports:
      - "8506:15672"
    volumes:
      - ./config/lavinmq0-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lavinmq0
    networks:
      - app-network

  lavinmq1-nginx:
    image: nginx:alpine
    container_name: lavinmq1-nginx
    ports:
      - "8507:15673"
    volumes:
      - ./config/lavinmq1-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lavinmq1
    networks:
      - app-network

  lavinmq2-nginx:
    image: nginx:alpine
    container_name: lavinmq2-nginx
    ports:
      - "8508:15674"
    volumes:
      - ./config/lavinmq2-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lavinmq2
    networks:
      - app-network

  # local-login:
  #   build: ./Local-Login
  #   container_name: local-login
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - local-db
  #   networks:
  #     - app-network

  # local-db:
  #   image: postgres:latest
  #   container_name: local-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: demo
  #   ports:
  #     - "5332:5432"
  #   volumes:
  #     - local-db-data:/var/lib/postgresql/data
  #     - ./Local-Login/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - app-network

  # storage-service:
  #   build: ./Storage-Service
  #   container_name: storage-service
  #   ports:
  #     - "8502:8502"
  #   depends_on:
  #     - local-db
  #   volumes:
  #     - ./config/config.yaml:/app/config/config.yaml:ro
  #     - ./config/message_broker_config.yaml:/app/config/message_broker_config.yaml:ro
  #   networks:
  #     - app-network

volumes:
  local-db-data:
  lavinmq0-data:
  lavinmq1-data:
  lavinmq2-data:
  synnax-data:

networks:
  app-network:
    driver: bridge
