name: tier-one-dev

services:
  fusion:
    build: ./Fusion
    container_name: fusion
    ports:
      - "8505:8505"
    volumes:
      - ./config/config.yaml:/config/config.yaml:ro
      - ./config/message_broker_config.yaml:/config/message_broker_config.yaml:ro
    networks:
      - tier-zero_app-network

networks:
  tier-zero_app-network:
    external: true
